version: '3.1'
services:

  db:
    container_name: db
    build: db/
    restart: always
    environment:
      # Essa variável de ambiente é obrigatória
      POSTGRES_PASSWORD: Bigarelli251162

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  etl:
    container_name: etl
    build: etl/
    ports:
      # - 8081:8081
      - 8000:8000
      - 8001:8001
    depends_on:
      - db
    volumes:
      - "./etl/out:/app/out"
      # - data:/app/out

  backend_cdp_service:
    container_name: backend_cdp_service
    build: backend-cdp-service/
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - db
      

  # backend:
  #   container_name: backend
  #   build: backend/
  #   ports:
  #     - 8082:8082
  #   depends_on:
  #     - db
  #     - updater

# volumes:
#   data:
