version: '3.1'
services:

  db:
    container_name: db
    build: db/
    restart: always
    environment:
      # Essa variável de ambiente é obrigatória
      POSTGRES_PASSWORD: Bigarelli251162

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  updater:
    container_name: updater
    build: updater/
    ports:
      - 8081:8081
    depends_on:
      - db

  # backend:
  #   container_name: backend
  #   build: backend/
  #   ports:
  #     - 8082:8082
  #   depends_on:
  #     - db
  #     - updater
